# Winter heat
#
# My home has all-electric heat, with a mix of electric baseboard and cieling radiant heat.
#
# I have bought some MySA thermostats to control the heat, with the HomeKit Device integration to control them.

# TODO: I've used anchors to simplify power usage, but I'm wondering if I can do something even 
# simpler with custom components or by generating HASS YAML from custom YAML.

# Power usage
template:
  - sensor:
    - &base_estimated_power_usage
      name: Living Room Heat Estimated Power Usage
      variables:
        baseline_power_usage: 1500 # 6ft baseboard heat
        source_entity: climate.living_room_baseboard_heat
      state: >
        {{ state_attr(source_entity, 'hvac_action') == 'heating' and baseline_power_usage | int or 0 }}
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      
    - <<: *base_estimated_power_usage
      name: Kitchen Baseboard Heat Estimated Power Usage
      variables:
        baseline_power_usage: 1000 # 4ft baseboard heat
        source_entity: climate.kitchen_baseboard_heat

    - <<: *base_estimated_power_usage
      name: Dining Room Radiant Heat Estimated Power Usage
      variables:
        baseline_power_usage: 1000  # ~100 sqft of radiant heat
        source_entity: climate.dining_room_heat

    - <<: *base_estimated_power_usage
      name: Play Room Baseboard Heat Estimated Power Usage
      variables:
        baseline_power_usage: 1000 # 4ft baseboard heat
        source_entity: climate.play_room_heat

    - <<: *base_estimated_power_usage
      name: Room 1 Baseboard Heat Estimated Power Usage
      unique_id: bed1_energy_usage
      variables:
        baseline_power_usage: 1000 # ~90 sqft of radiant heat
        source_entity: climate.bed1_heat
      
    - <<: *base_estimated_power_usage
      name: Room 2 Baseboard Heat Estimated Power Usage
      unique_id: bed2_energy_usage
      variables:
        baseline_power_usage: 1000 # ~90 sqft of radiant heat
        source_entity: climate.bed2_heat

sensor:
  - &base_power_usage_sensor
    platform: integration
    source: sensor.living_room_heat_estimated_power_usage
    name: Living Room Heat Power Usage
    unit_prefix: k
    unit_time: h
    round: 2
    method: left  # Best for rectangular pulses
    max_sub_interval: 
      minutes: 1
  
  - <<: *base_power_usage_sensor
    name: Kitchen Heat Power Usage
    source: sensor.kitchen_baseboard_heat_estimated_power_usage
  
  - <<: *base_power_usage_sensor
    name: Dining Room Radiant Heat Power Usage
    source: sensor.dining_room_radiant_heat_estimated_power_usage
  
  - <<: *base_power_usage_sensor
    name: Play Room Baseboard Heat Power Usage
    source: sensor.play_room_baseboard_heat_estimated_power_usage

  - <<: *base_power_usage_sensor
    name: Room 1 Baseboard Heat Power Usage
    source: sensor.room_1_baseboard_heat_estimated_power_usage
    unique_id: bed1_energy_usage
  
  - <<: *base_power_usage_sensor
    name: Room 2 Baseboard Heat Power Usage
    source: sensor.room_2_baseboard_heat_estimated_power_usage
    unique_id: bed2_energy_usage

utility_meter:
  living_room_heat_monthly:
    name: Living Room Heat Monthly Power Usage
    source: sensor.living_room_heat_power_usage
    cycle: monthly
  kitchen_heat_monthly:
    name: Kitchen Heat Monthly Power Usage
    source: sensor.kitchen_heat_power_usage
    cycle: monthly
  dining_room_heat_monthly:
    name: Dining Room Heat Monthly Power Usage
    source: sensor.dining_room_radiant_heat_power_usage
    cycle: monthly
  play_room_heat_monthly:
    name: Play Room Heat Monthly Power Usage
    source: sensor.play_room_baseboard_heat_power_usage
    cycle: monthly
  room_1_heat_monthly:
    name: Room 1 Heat Monthly Power Usage
    source: sensor.room_1_baseboard_heat_power_usage
    cycle: monthly
  room_2_heat_monthly:
    name: Room 2 Heat Monthly Power Usage
    source: sensor.room_2_baseboard_heat_power_usage
    cycle: monthly

# Power derivative
# Helps me keep track of how well each heater is performing. Hopefully this will give me data
# to more efficiently heat my home.

sensor derivative:
  - platform: derivative
    source: sensor.living_room_temperature
    name: Living Room Temperature Change Rate
  - platform: derivative
    source: sensor.kitchen_temperature
    name: Kitchen Temperature Change Rate
  - platform: derivative
    source: sensor.dining_room_temperature
    name: Dining Room Temperature Change Rate
  - platform: derivative
    source: sensor.play_room_heat_temperature
    name: Play Room Temperature Change Rate
  - platform: derivative
    source: sensor.room_1_temperature
    unique_id: bed1_temperature_change_rate
    name: Room 1 Temperature Change Rate
  - platform: derivative
    source: sensor.room_2_temperature
    unique_id: bed2_temperature_change_rate
    name: Room 2 Temperature Change Rate
