name: Deploy Home Assistant configuration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run tests
        steps:
            - name: Check out from GitHub
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install .
            - name: Run tests
              run: pytest -vv

    path_check:
        runs-on: ubuntu-latest
        name: Check path
        steps:
            - name: Check out from GitHub
              uses: actions/checkout@v3
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                filters: |
                  config:
                    - 'homeassistant/**'

    check_config:
        runs-on: ubuntu-latest
        name: Check Home Assistant config
        needs: path_check
        if: needs.path_check.outputs.config == 'true'
        steps:
            - name: Check out from GitHub
              uses: actions/checkout@v3
            - name: Check configuration
              uses: frenck/action-home-assistant@v1
              with:
                path: "./config"
                secrets: secrets.yaml.tpl
                version: stable
        
    
    deploy:
        runs-on: ubuntu-latest
        name: Deploy Home Assistant
        needs:
            - path_check
            - test
            - check_config
        if: needs.path_check.outputs.config == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Check out from GitHub
              uses: actions/checkout@v3
            - name: Install 1Password CLI
              uses: 1password/install-cli-action@v1
            - name: Set up AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: us-east-1
            - name: Inject 1Password secrets
              env:
                OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
                OP_VAULT: ${{ secrets.OP_VAULT }}
              run: |
                for infile in homeassistant/**/*.tpl; do
                  outfile="${infile%.tpl}"
                  op inject -f -i $infile -o $outfile
                done
            - name: Tar configuration
              run: tar -czf - homeassistant | openssl enc -aes-256-cbc -e -k ${{ secrets.ENCRYPTION_KEY }} -out homeassistant.tar.gz.enc
            - name: Publish to S3
              env:
                S3_PATH: "s3://${{ secrets.S3_BUCKET }}/$(date +%Y/%m/%d)/$(date +%H%M%S)_${{ github.sha }}_homeassistant.tar.gz.enc"
              run: |
                aws s3 cp homeassistant.tar.gz.enc $S3_PATH
            - name: Save S3 path
              id: s3path
              run: echo "s3_path=$S3_PATH" >> $GITHUB_ENV
            - name: Push to Home Assistant
              run: |
                curl -X POST -H "Content-Type: application/json" -d "{\"presigned_url\": \"$S3_PATH\"}" ${{ secrets.webhook_ci_push }}




